# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 960a1d7876d0835d7c61e991bbc8c69b0e9de51d9d199987be61b0cff86ef90ca6097fd31801e0f8aac7799a5c27bc27aacd2eb5eccb59a4886c6f26765da547

test:
  secret_key_base: 59aaddf4311b1bd845a544f83a12b3a3ddd62886533c36583d8abe4f43bf7d13777d6a55cf8f60e7d65ce367d54eba41ba38b4b26db09a6cb0f1633a513d1b72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
